# Site settings
title: Sebastiano
retailer: Sebastiano
description: "Sebastiano Mastroeni - Super project director"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: none
destination: build
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - yarn.lock
  - node_modules
