# Site settings
title: "Sebastiano Mastroeni - Super project director"
retailer: Sebastiano
description: "discover what Sebastiano Mastroeni does in a couple of clicks"
baseurl: ""
url: "http://www.sebastianomastroeni.com"

# Build settings
markdown: kramdown
permalink: none
destination: build
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - yarn.lock
  - node_modules
