#!/bin/bash

# Retrive current active branch
get_current_branch() {
    echo `git rev-parse --abbrev-ref HEAD`
}

# Check if current branch is master
# If current branch isn't master, then exit with status=1
CURRENT_BRANCH=$(get_current_branch)

if [ $CURRENT_BRANCH != "develop" ]
  then
    echo "Unable to release. To proceed with a new release change to current branch to MASTER."
    exit 1
fi

# Update develop branch
git pull --rebase origin develop

# Update repository libraries dependencies
yarn install

# Compile static assets
gulp build

# Tag new release
git checkout -b releasing
git add -f assets
git rm -r _gulp-tasks _src .ruby-version .gitignore .nvmrc gulpfile.js package.json release yarn.lock
git commit -m "New release"
git push origin releasing:gh-pages

#Back to master
git checkout develop

#Delete releasing branch
git branch -D releasing

